### ISSUE TITLE
Pybind error

### ISSUE THREAD

**Issue by sameer56** [gdlg/pytorch_nms#1]
Hi,
 Using Pytorch 1.0
 Iam facing this issue while building the extension

/home/teai/pramod/pytorch_env/lib/python3.5/site-packages/torch/lib/include/pybind11/cast.h:2096:44: error: no matching function for call to ‘collect_arguments(pybind11::handle&, pybind11::handle&)’
     return detail::collect_arguments<policy>(std::forward<Args>(args)...).call(derived().ptr());

**Comment by gdlg** [comment]
Hi,

I have never encountered this error before and I would think that it is linked to your environment. Which Linux distribution & version are you using? Which version of GCC? Which version of CUDA?

**Comment by sameer56** [comment]
Hi, Iam using cuda 10.0version and ubuntu 16.04LTSOn 22-Feb-2019 5:00 AM, Grégoire Payen de La Garanderie <notifications@github.com> wrote:Hi,
I have never encountered this error before and I would think that it is linked to your environment. Which Linux distribution & version are you using? Which version of GCC? Which version of CUDA?

**Comment by sameer56** [comment]
Hi, Iam using 5.4.0 GCC versionOn 22-Feb-2019 9:33 AM, sameerkumar0312@yahoo.com wrote:Hi, Iam using cuda 10.0version and ubuntu 16.04LTSOn 22-Feb-2019 5:00 AM, Grégoire Payen de La Garanderie <notifications@github.com> wrote:Hi,
I have never encountered this error before and I would think that it is linked to your environment. Which Linux distribution & version are you using? Which version of GCC? Which version of CUDA?

**Comment by gdlg** [comment]
I am not able to reproduce your problem. I highly suspect that the problem might be due to your older version of GCC. Could you try with a more recent version of GCC? It should work with GCC 7.3.0 provided with Ubuntu 18.04.

**Comment by CasonTsai** [comment]
hello, i met a problem when use nvcc to compiled this project 。
`i use  'nvcc -o cudatest nms_kernel.cu -L -lcudart -I D:\Code-software\NNF\libtorch\libtorch\include -I D:\Code-software\NNF\libtorch\libtorch\include\torch\csrc\api\include`  to compiled it ,
but get the  error: member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized
